group("hawk_logger_all") {
  public_deps = [
    ":hawk_logger",
  ]
}

static_library("hawk_logger") {
  configs += [ ":hawk_logger_config" ]
  sources = [
    "check.h",
    "check.cc",
    "file_util.h",
    "file_util.cc",
    "logging.h",
    "logging.cc",
    "logging_base.h",
  ]
}

config("hawk_logger_config") {
  include_dirs = [
    "./",
  ]
}


