group("mini_logger_all") {
  public_deps = [
    ":mini_logger",
  ]
}

static_library("mini_logger") {
  configs += [ ":mini_logger_config" ]
  sources = [
    "check.h",
    "check.cc",
    "console.h",
    "console.cc",
    "file_util.h",
    "file_util.cc",
    "logging.h",
    "logging.cc",
    "logging_base.h",
  ]
}

config("mini_logger_config") {
  defines = [ "HAWK_LOGGER" ]
  include_dirs = [
    "./",
  ]
}


