# Copyright 2025 Alex313031

group("cryocalc_all") {
  public_deps = [
    ":cryocalc",
    "osinfo:osinfo_dll",
    "src/logging:mini_logger_all",
  ]
}

executable("cryocalc") {
  configs -= [ "//build/config/win:console_subsystem" ]
  configs += [
    "//build/config/win:windowed_subsystem",
    ":cryocalc_config",
    "src/logging:mini_logger_config",
  ]
  sources = [
    "src/constants.h",
    "src/controls.cc",
    "src/controls.h",
    "src/converters.cc",
    "src/converters.h",
    "src/cryocalc.cc",
    "src/cryocalc.h",
    "src/framework.h",
    "src/globals.h",
    "src/osinfo_window.h",
    "src/osinfo_window.cc",
    "src/painting.h",
    "src/painting.cc",
    "src/resource.h",
    "src/resource.rc",
    "src/strings.h",
    "src/stress/stress.h",
    "src/stress/stress.cc",
    "src/utils.cc",
    "src/utils.h",
    "src/version.h",
  ]
  deps = [
    "osinfo:osinfo",
    "src/logging:mini_logger",
  ]
  public_deps = [
    "osinfo:osinfo_dll",
  ]
}

config("cryocalc_config") {
  include_dirs = [
    "src",
    "osinfo",
  ]
  # Track unused functions
  cflags = [ "-Wunused-function" ]
}
