# Copyright 2026 Alex313031

group("cryocalc_all") {
  public_deps = [
    ":cryocalc",
    "osinfo:osinfo_dll",
    "src/logging:mini_logger_all",
  ]
}

executable("cryocalc") {
  configs += [
    ":cryocalc_config",
    "src/logging:mini_logger_config",
  ]
  sources = [
    "src/constants.h",
    "src/controls.cc",
    "src/controls.h",
    "src/converters.cc",
    "src/converters.h",
    "src/cryocalc.cc",
    "src/cryocalc.h",
    "src/framework.h",
    "src/globals.h",
    "src/monitor_window.h",
    "src/monitor_window.cc",
    "src/osinfo_window.h",
    "src/osinfo_window.cc",
    "src/painting.h",
    "src/painting.cc",
    "src/resource.h",
    "src/resource.rc",
    "src/strings.h",
    "src/stress/common.h",
    "src/stress/cpu.h",
    "src/stress/cpu.cc",
    "src/stress/io.h",
    "src/stress/io.cc",
    "src/stress/mem.h",
    "src/stress/mem.cc",
    "src/stress/reporting.h",
    "src/stress/reporting.cc",
    "src/stress/stress.h",
    "src/stress/stress.cc",
    "src/utils.cc",
    "src/utils.h",
    "src/ui_utils.cc",
    "src/ui_utils.h",
    "src/version.h",
  ]
  deps = [
    "osinfo:osinfo",
    "src/logging:mini_logger",
  ]
  public_deps = [
    "osinfo:osinfo_dll",
  ]
}

config("cryocalc_config") {
  include_dirs = [
    "src",
    "osinfo",
  ]
  # Track unused functions
  cflags = [ "-Wunused-function" ]
  libs = [ "winmm", ]
}
