# Cryocalc INI file

# Default precision to use for temp calculations
precision=4

# Whether to enable debug mode (and console logging)
debug_mode=1

# Whether to enable console logging (not implemented yet)
#enable_logging=1
